### ISSUE TITLE
Landing page UI implementation

### ISSUE THREAD

**Issue by bandungdev-com** [bandungdevcom/bandungdev.com#1]
- Hero and Introduction
- Photos
- Upcoming Events & Past Events
- Latest Members Joined

**Comment by abui-am** [comment]
ini gw coba ambil aja ya

**Comment by mhaidarhanif** [comment]
@abui-am Yes please do so

**Comment by mhaidarhanif** [comment]
@abui-am and @fikrialwan can work together to improve the landing page.
