### ISSUE TITLE
User settings to manage links such as social media and websites

### ISSUE THREAD

**Issue by mhaidarhanif** [bandungdevcom/bandungdev.com#20]
# Feature request

## Is the feature request related to a problem? Please describe

Currently the user profile only has headline and bio.

## Describe the solution

Other than those, also need the CRUD to have links/urls for social media and websites.

## Additional context

Need to utilize the existing model of UserProfile links field (JSON). Also create a new form component that can handle the CRUD, leveraging Conform library.

For example:

```json
[
  { "url": "https://example.com", "name": "Example" },
  { "url": "https://github.com/example", "name": "GitHub" }
]
```

Can also check how similar project, Bearmentor accomplish this:

- https://bearmentor.com/haidar
- https://github.com/bearmentor/bearmentor
  - https://github.com/bearmentor/bearmentor/blob/main/app/routes/settings.profile.tsx
  
But make it simpler or following the convention in this BandungDev repo.

**Comment by agus-wesly** [comment]
https://github.com/bandungdevcom/bandungdev.com/pull/24
