### ISSUE TITLE
User settings to change avatar or profile picture

### ISSUE THREAD

**Issue by mhaidarhanif** [bandungdevcom/bandungdev.com#29]
# Feature request

## Is the feature request related to a problem? Please describe

User can already have an avatar, but it was automatic only from GitHub or Google account.

## Describe the solution

User can customize avatar by image upload, using the Uploacare component.

## Additional context

Can check the example at https://staging.bandungdev.com/examples/uploadcare

**Comment by agus-wesly** [comment]
https://github.com/bandungdevcom/bandungdev.com/assets/98297487/51f0f228-480a-4314-8768-8adbad4677a4

This is the first look of the edit avatar feature. I change the ui a little bit. What do you guys think ?

**Comment by agus-wesly** [comment]
[Kazam_screencast_00000.webm](https://github.com/bandungdevcom/bandungdev.com/assets/98297487/b1d416aa-d8ff-42cd-932e-7fa3c2532332)

This is initial UI & first look of this feature. What do you think ??

**Comment by mhaidarhanif** [comment]
@agus-wesly All good, can create the PR
