### ISSUE TITLE
User settings to change profile details

### ISSUE THREAD

**Issue by bandungdev-com** [bandungdevcom/bandungdev.com#3]
- Headline
- Bio

No need to update avatar or profile picture, it already handled automatically when connecting with GitHub or Google account.

**Comment by agus-wesly** [comment]
![image](https://github.com/bandungdevcom/bandungdev.com/assets/98297487/5bb8aabe-09b9-45de-a795-e73962698b50)

Just to confirm, these 2 inputs (Headline and bio) will be placed below the Nickname input, right ?
